extends:
  - "react-app"
  - "react-app/jest"
  - "plugin:jest-dom/recommended"
  - "plugin:functional/external-recommended"
  - "plugin:functional/lite"
rules:
  react/self-closing-comp:
    - error
    - component: true
      html: true
plugins:
  - "jest-dom"
  - "functional"
