enableScripts: false

enableTelemetry: 0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
packageExtensions:
  "@material-ui/pickers@*":
    dependencies:
      "prop-types": "*"
  "jss-plugin-rule-value-function@*":
    dependencies:
      "tiny-warning": "*"
